language: node_js
cache:
  directories:
    - $HOME/.npm
    - node_modules
os:
  - linux
  - osx
  - windows
node_js:
  - '12'
  - '10'
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
      git config --global core.autocrlf false
      cd ../..
      mv $TRAVIS_REPO_SLUG _old
      git clone _old $TRAVIS_REPO_SLUG
      cd $TRAVIS_REPO_SLUG
    fi
install:
  - npm ci
  - npx lerna bootstrap --hoist --no-ci
script:
  - npm run build
  - npm test
