language: node_js
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - modules-dom/data-viewer/node_modules
    - modules-es/catalog/node_modules
    - modules-es/date-tools/node_modules
    - modules-es/number-tools/node_modules
    - modules-es/object-tools/node_modules
    - modules-es/string-tools/node_modules
    - modules-node/cli-tools/node_modules
    - modules-node/config-validator/node_modules
    - modules-node/fs-tools/node_modules
    - modules-node/net-tools/node_modules
    - modules-node/server/node_modules
    - modules-node/stream-tools/node_modules
os:
  - linux
  - osx
  - windows
node_js:
  - '12'
  - '10'
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
      git config --global core.autocrlf false
      cd ../..
      mv $TRAVIS_REPO_SLUG _old
      git clone _old $TRAVIS_REPO_SLUG
      cd $TRAVIS_REPO_SLUG
    fi
install:
  - npm ci
  - npx lerna bootstrap --no-ci
script:
  - npm run build
  - npm test
