version: 2.1
jobs:
  onBranch:
    docker: [{image: "alpine:latest"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH ]]; then exit 1; fi
  onDevelopBranch:
    docker: [{image: "alpine:latest"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH || $CIRCLE_BRANCH == "master" ]]; then exit 1; fi
  onMasterBranch:
    docker: [{image: "alpine:latest"}]
    steps:
      - run: if [[ $CIRCLE_BRANCH != "master" ]]; then exit 1; fi
  isTagged:
    docker: [{image: "alpine:latest"}]
    steps:
      - run: if [[ -z $CIRCLE_TAG ]]; then exit 1; fi
  setup:
    docker: [{image: "keiitof/node:latest"}]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run: npm ci
      - run: npx lerna bootstrap --no-ci
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace: {root: ., paths: [.]}
  lint:
    docker: [{image: "keiitof/node:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run lint
  build:
    docker: [{image: "keiitof/node:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run build
      - run: git diff --exit-code
      - persist_to_workspace: {root: ., paths: [.]}
  test-configurations:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npm run test:repo}]
  test-data-viewer:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/data-viewer}]
  test-catalog:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/catalog}]
  test-date-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/date-tools}]
  test-number-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/number-tools}]
  test-object-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/object-tools}]
  test-string-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/string-tools}]
  test-cli-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/cli-tools}]
  test-config-validator:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/config-validator}]
  test-fs-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/fs-tools}]
  test-net-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/net-tools}]
  test-server:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/server}]
  test-stream-tools:
    docker: [{image: "keiitof/node:latest"}]
    steps: [{attach_workspace: {at: .}}, {run: npx lerna run test --parallel --scope @maxi-js/stream-tools}]
  report-test-results:
    docker: [{image: "keiitof/node:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: echo 'All tests were passed successfully.'
  deploy-server:
    docker: [{image: "keiitof/aws-sam:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: sam package --template-file modules-node/server/template.yml --output-template-file modules-node/server/output-template.yml --s3-bucket $S3_BUCKET
      - run: aws cloudformation deploy
              --template-file modules-node/server/output-template.yml
              --stack-name maxiapp-server
              --capabilities CAPABILITY_IAM
              --no-fail-on-empty-changeset
  deploy-cdn:
    docker: [{image: "keiitof/aws-cli:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: aws s3 sync cdn s3://$S3_BUCKET/
              --cache-control "max-age=31536000, public, immutable"
  deploy-data-viewer:
    docker: [{image: "keiitof/aws-cli:latest"}]
    steps:
      - attach_workspace: {at: .}
      - run: aws s3 sync modules-dom/data-viewer/output s3://$S3_BUCKET/data-viewer/
              --cache-control "max-age=31536000, public, immutable"
              --exclude "*.html"
workflows:
  version: 2
  run-tests:
    jobs:
      - onBranch:
          filters: {branches: {only: /.*/}, tags: {ignore: /.*/}}
      - setup: {requires: [onBranch]}
      - lint: {requires: [setup]}
      - build: {requires: [setup]}
      - test-configurations: {requires: [build]}
      - test-data-viewer: {requires: [build]}
      - test-catalog: {requires: [build]}
      - test-date-tools: {requires: [build]}
      - test-number-tools: {requires: [build]}
      - test-object-tools: {requires: [build]}
      - test-string-tools: {requires: [build]}
      - test-cli-tools: {requires: [build]}
      - test-config-validator: {requires: [build]}
      - test-fs-tools: {requires: [build]}
      - test-net-tools: {requires: [build]}
      - test-server: {requires: [build]}
      - test-stream-tools: {requires: [build]}
      - report-test-results:
          requires:
            - test-configurations
            - test-data-viewer
            - test-catalog
            - test-date-tools
            - test-number-tools
            - test-object-tools
            - test-string-tools
            - test-cli-tools
            - test-config-validator
            - test-fs-tools
            - test-net-tools
            - test-server
            - test-stream-tools
  release:
    jobs:
      - isTagged:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - setup:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [isTagged]
      - lint:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [setup]
      - build:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [setup]
      - test-configurations:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-data-viewer:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-catalog:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-date-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-number-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-object-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-string-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-cli-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-config-validator:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-fs-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-net-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-server:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - test-stream-tools:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [build]
      - report-test-results:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires:
            - test-configurations
            - test-data-viewer
            - test-catalog
            - test-date-tools
            - test-number-tools
            - test-object-tools
            - test-string-tools
            - test-cli-tools
            - test-config-validator
            - test-fs-tools
            - test-net-tools
            - test-server
            - test-stream-tools
      - deploy-server:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [report-test-results]
      - deploy-data-viewer:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [report-test-results]
      - deploy-cdn:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
          requires: [report-test-results]
