version: 2.1
jobs:
  onBranch:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH ]]; then exit 1; fi
  onDevelopBranch:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH || $CIRCLE_BRANCH == "master" ]]; then exit 1; fi
  onMasterBranch:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ $CIRCLE_BRANCH != "master" ]]; then exit 1; fi
  isTagged:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_TAG ]]; then exit 1; fi
  setup:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run: npm ci
      - run: npx lerna bootstrap --no-ci
      - save_cache:
          paths:
            - node_modules
            - modules-dom/data-viewer/node_modules
            - modules-node/cli-tools/node_modules
            - modules-node/config-validator/node_modules
            - modules-node/fs-tools/node_modules
            - modules-node/server/node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace: {root: ., paths: [.]}
  lint:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run lint
  build:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run build
      - run: git diff --exit-code
      - persist_to_workspace: {root: ., paths: [.]}
  test-server:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npx lerna run test --scope @maxi-js/server
  test-data-viewer:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npx lerna run test --scope @maxi-js/data-viewer
  deploy-server:
    docker: [{image: "keiitof/awscli-nodejs:0.0.2"}]
    steps:
      - attach_workspace: {at: .}
      - run: cd modules-node/server
      - run: sam package --template-file server/template.yml --output-template-file server/output-template.yml --s3-bucket $S3_SERVERAPP_BUCKET
      - run: aws cloudformation deploy
              --template-file server/output-template.yml
              --stack-name maxiapp-server
              --capabilities CAPABILITY_IAM
              --no-fail-on-empty-changeset
  deploy-data-viewer:
    docker: [{image: "keiitof/awscli-nodejs:0.0.2"}]
    steps:
      - attach_workspace: {at: .}
      - run: cd modules-dom/data-viewer
      - run: aws s3 cp client/output s3://$S3_CLIENTAPP_BUCKET/ --recursive
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html
workflows:
  version: 2
  run-tests:
    jobs:
      - onBranch:
          filters: {branches: {only: /.*/}, tags: {ignore: /.*/}}
      - setup: {requires: [onBranch]}
      - lint: {requires: [setup]}
      - build: {requires: [setup]}
      - test-server: {requires: [build]}
      - test-data-viewer: {requires: [build]}
  release:
    jobs:
      - isTagged:
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - setup:
          requires: [isTagged]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - lint:
          requires: [setup]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - build:
          requires: [setup]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - test-server:
          requires: [build]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - test-data-viewer:
          requires: [build]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - deploy-server:
          requires: [test-server]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
      - deploy-data-viewer:
          requires: [test-data-viewer]
          filters: {branches: {ignore: /.*/}, tags: {only: /^v.*/}}
