AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals:
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6
    Runtime: nodejs8.10

Resources:
  IndexFunction:
    # More info about Function Resource:
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/
      Handler: index.handler
      Events:
        HttpGet:
          # More info about API Event Source:
          # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            Path: /objects
            Method: get
  ObjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/
      Handler: object.handler
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /objects/{objectId}
            Method: get
